# syntax=docker/dockerfile:1
# escape=`
ARG TAG_BUILD=10.0.20348.1
ARG TAG_FINAL=6.0.21-nanoserver-ltsc2022
# Image with msiexec
FROM mcr.microsoft.com/windows/servercore/insider:$TAG_BUILD as build

LABEL maintainer="Oleksis Fraga <oleksis.fraga at gmail.com>"
LABEL org.opencontainers.image.source=https://github.com/oleksis/setup-mpdev
LABEL org.opencontainers.image.description="Setup Master Packager Dev"
LABEL org.opencontainers.image.licenses=MIT

RUN curl.exe -L -o mpdev_self_contained_x64_1.0.4.msi https://oleksis.github.io/setup-mpdev/download/mpdev_self_contained_x64_1.0.4.msi `
    && msiexec /i mpdev_self_contained_x64_1.0.4.msi /qn `
    && del /F mpdev_self_contained_x64_1.0.4.msi

# final stage/image
FROM mcr.microsoft.com/dotnet/runtime:$TAG_FINAL
# hadolint shell=powershell
ENV MPDEV_HOME='C:\Program Files\Master Packager Ltd\Master Packager Dev'
ENV WINDIRSYS32='C:\WINDOWS\System32'
# TODO: Fix Building MSI
# mpdev: error: Unable to load DLL 'msi.dll' or one of its dependencies: The specified procedure could not be found. (0x8007007F)
COPY --from=build ${MPDEV_HOME} ${MPDEV_HOME}
COPY --from=build ${WINDIRSYS32}\msiexec.exe `
                  ${WINDIRSYS32}\msi.dll `
                  ${WINDIRSYS32}\msihnd.dll `
                  ${WINDIRSYS32}\msisip.dll ${WINDIRSYS32}/

USER ContainerAdministrator
RUN setx /m PATH "%MPDEV_HOME%;%PATH%" `
    && mkdir C:\src
# USER ContainerUser

VOLUME C:\src
# WORKDIR /src

ENTRYPOINT ["mpdev.exe"]
