# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Packaging .NET app to MSI/MSIX with MPDev

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_SHORT: setup-mpdev
  IMAGE_NAME: ${{ github.repository }}
  SHA: ${{ github.event.pull_request.head.sha || github.event.after }}

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: read
      pull-requests: read

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore Publish Run
        run: |
          pushd apptest
          dotnet restore
          dotnet publish -f net6.0 -r win-x64 --self-contained false
          popd

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      # mpdev.exe on Docker need to return Exit code 1 when error: Status: FAILED
      - name: MPDev MSI/MSIX
        run: |
          docker run --name mpdev-hello -i --workdir /src -v .:C:\src ghcr.io/oleksis/setup-mpdev:v1 build apptest/mpdev.json --working-dir C:\src --verbose

      - name: Display Directory
        run: tree /F /A .

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mpdev-hello
          path: "./dist/mpdev-hello_1.0.0_x64.msi"
          if-no-files-found: error
